apiVersion: v2
name: infra-cluster
description: Cluster-scoped infrastructure components (ingress-nginx, etc.)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.13.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
