{{- if and .Values.storage.minio.enabled .Values.storage.minio.ingress.enabled }}
{{- $fullName := include "infra.fullname" . }}
{{- $consolePort := .Values.storage.minio.service.consolePort | default 9001 }}
{{- if and .Values.storage.minio.ingress.className (not (hasPrefix "nginx" .Values.storage.minio.ingress.className)) }}
{{- fail "Only nginx ingress controller is supported" }}
{{- end }}
{{- range .Values.storage.minio.ingress.hosts }}
{{- $host := .host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-minio-console
  labels:
    {{- include "infra.labels" $ | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with $.Values.storage.minio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.storage.minio.ingress.className }}
  ingressClassName: {{ $.Values.storage.minio.ingress.className }}
  {{- end }}
  {{- if $.Values.storage.minio.ingress.tls }}
  tls:
    {{- range $.Values.storage.minio.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .paths }}
    - host: {{ $host | quote }}
      http:
        paths:
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $fullName }}-minio
              port:
                number: {{ $consolePort }}
    {{- end }}
{{- end }}
{{- end }}
