{{- if and .Values.storage.minio.enabled .Values.storage.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infra.fullname" . }}-minio-pvc
  labels:
    {{- include "infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - {{ .Values.storage.minio.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.storage.minio.persistence.size | default "10Gi" }}
  {{- if .Values.storage.minio.persistence.storageClass }}
  storageClassName: {{ .Values.storage.minio.persistence.storageClass }}
  {{- end }}
{{- end }}
