{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
{{- $fullName := include "lendahand.fullname" . }}
{{- $svcPort := .Values.backend.service.port }}
{{- if and .Values.backend.ingress.className (not (hasPrefix "nginx" .Values.backend.ingress.className)) }}
{{- fail "Only nginx ingress controller is supported" }}
{{- end }}
{{- range .Values.backend.ingress.hosts }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-backend
  labels:
    {{- include "lendahand.backend.labels" $ | nindent 4 }}
  {{- with $.Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.backend.ingress.className }}
  ingressClassName: {{ $.Values.backend.ingress.className }}
  {{- end }}
  {{- if $.Values.backend.ingress.tls }}
  tls:
    {{- range $.Values.backend.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .paths }}
    - host: {{ $.host | quote }}
      http:
        paths:
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $fullName }}-backend
              port:
                number: {{ $svcPort }}
    {{- end }}
{{- end }}
{{- end }}

