{{- if .Values.backend.enabled }}
{{- range .Values.backend.volumes }}
{{- if .persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .persistentVolumeClaim.claimName }}
  labels:
    {{- include "lendahand.backend.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if $.Values.global.storageClass }}
  storageClassName: {{ $.Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 10Gi
{{- end }}
{{- end }}
{{- end }}

