{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lendahand.fullname" . }}-backend-secret
  labels:
    {{- include "lendahand.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.backend.env.DJANGO_SECRET_KEY | quote }}
  STRIPE_SECRET_KEY: {{ .Values.backend.env.STRIPE_SECRET_KEY | quote }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.backend.env.STRIPE_PUBLISHABLE_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.backend.env.STRIPE_WEBHOOK_SECRET | quote }}
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
{{- end }}

