{{- if .Values.storage.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lendahand.fullname" . }}-minio-secret
  labels:
    {{- include "lendahand.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
type: Opaque
stringData:
  root-user: {{ .Values.storage.minio.auth.rootUser | default "minioadmin" | quote }}
  root-password: {{ .Values.storage.minio.auth.rootPassword | default "minioadmin" | quote }}
{{- end }}
