apiVersion: v2
name: infra
description: Namespace-scoped infrastructure components (PostgreSQL, MinIO)

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql                 # the subchart's name (as published)
    version: 15.5.25                 # pin a specific version
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled    # (optional) allow toggling via values
