name: 'CD'


on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'cicd'
    paths:
      - "backend/**"
      - "devops/**"


env:
  PROJECT_ID: 'test-donate-472114'
  GAR_LOCATION: 'us-central1'
  GKE_CLUSTER: 'lendahand-test'
  GKE_ZONE: 'us-central1-a'
  REPOSITORY: 'donatereg'
  IMAGE: 'backend'
  IMAGEFRONT: 'frontend'

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet


      - name: Get GKE credentials (no plugin needed)
        uses: google-github-actions/get-gke-credentials@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}


      - name: 'Build and push Docker container back'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            backend
          docker push "${DOCKER_TAG}"
          echo "Pushed:" "${DOCKER_TAG}"

      - name: 'Build and push Docker container frontend'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGEFRONT}:${GITHUB_SHA}"
          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            frontend
          docker push "${DOCKER_TAG}"
          echo "Pushed:" "${DOCKER_TAG}"


      - name: 'Deploy GKE'
        run: |-
          echo "Using a hash commit:"${GITHUB_SHA}
          helm upgrade --install lendahand devops/lendahand \
            --set backend.image.tag=${GITHUB_SHA} \
            --set frontend.image.tag=${GITHUB_SHA} \
            --set backend.env.STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            --set backend.env.STRIPE_PUBLISHABLE_KEY="${{ secrets.STRIPE_PUBLISHABLE_KEY }}" \
            --set backend.env.STRIPE_WEBHOOK_SECRET="${{ secrets.STRIPE_WEBHOOK_SECRET }}"
          kubectl get pods -A
