name: 'Build and Deploy to GKE Infra'

on:
  workflow_dispatch:
  push:
    paths:
      - "devops/infra/**"
    branches:
      - 'main'
      - 'cicd'

env:
  PROJECT_ID: 'test-donate-472114'
  GAR_LOCATION: 'us-central1'
  GKE_CLUSTER: 'lendahand-testenv'
  GKE_ZONE: 'us-central1-a'


jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet


      - name: Get GKE credentials (no plugin needed)
        uses: google-github-actions/get-gke-credentials@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}  

      - name: 'Build and push Docker container storage minio'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/storageminio:${GITHUB_SHA}"
          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            storage
          docker push "${DOCKER_TAG}"
          echo "Pushed:" "${DOCKER_TAG}"


      - name: 'Deploy to GKE'
        run: |-
          helm upgrade infra devops/infra 
          kubectl get pods -A
